on:
  push:
    branches:
      - master
name: Deploy to Github Pages
jobs:
  lektorBuild:
    name: lektor build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: lektor build
      uses: docker://softinstigate/lektor:3.1.2
      with:
        args: build
    - name: deploy to github pages
      uses: docker://softinstigate/lektor
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: 'deploy ghpages --username dschep --password "${{ secrets.GITHUB_TOKEN }}"'
